//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozyczalnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochod
    {
        public int Id { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public System.DateTime Rok { get; set; }
        public int LimitKilometrow { get; set; }
        public string Opony { get; set; }
        public bool AC { get; set; }
        public string NrRejestracyjny { get; set; }
        public byte[] Zdjecie { get; set; }
        public Nullable<decimal> Cena { get; set; }
    }
}
